### ISSUE TITLE
Error: SHM extension unavailable.

### ISSUE THREAD

**Issue by napejuice** [jaelpark/chamferwm#10]
libxcb is installed of course... :(

System:
  Host: jfpc Kernel: 5.2.9-22-tkg-pds x86_64 bits: 64 Desktop: Xfce 4.14.1 
  Distro: Arch Linux 
Graphics:
  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 430.40 
  Display: x11 server: X.Org 1.20.5 driver: nvidia 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 430.40

**Comment by jaelpark** [comment]
Shared memory pixmaps may not be available on NVIDIA by default. What happens if you put this to your xorg configuration?
`Option  "AllowSHMPixmaps" "1"`

**Comment by napejuice** [comment]
Uhh, do I place that under 'Section "Device"' ?

**Comment by jaelpark** [comment]
Yea, I found that people generally put it under there. I also found `Section "ServerFlags"`, and even "Screen" so I'm thinking if it makes any difference.

**Comment by napejuice** [comment]
That certainly did the trick but a whole heap of problems for me occurred such as windows not appearing and the titlebar and buttons missing. I'm going to assume it's because I need to configure everything or it's an nvidia problem. ¯\ _ _(ツ)_ _ /¯

**Comment by dedguy21** [comment]
Using the above method I can login to the environment, but I see nothing. I know the windows are present because Even though I can't see it when I enter the commands to pull up a terminal and type reboot, My system reboots. Again all this is invisible to me. 

Nvidia-440-86-dkms driver
Nvidia 730m card
Intel haswell i7 processor
