### ISSUE TITLE
Cursor does not show when chamferwm first started

### ISSUE THREAD

**Issue by juanitotc** [jaelpark/chamferwm#3]
When chamferwm is first started the cursor does not show.

I am obliged to move the mouse blind until it rolls over the wbar dock and the cursor appears, so I can launch an app.

If the app launches full screen, then the cursor remains for the rest of the session. If the app launches part screen, then the cursor is not visible over the background.

**Comment by jaelpark** [comment]
The reason is probably that chamferwm doesn't do any cursor loading at any point. Not yet at least. I haven't even noticed, usually as soon as the wm starts, I just launch some application with a hotkey, and the cursor then gets loaded by that application. But I will look into this, shouldn't be too difficult to fix.

**Comment by juanitotc** [comment]
It works now - thanks
