### ISSUE TITLE
Switching ttys crashes chamfer

### ISSUE THREAD

**Issue by rien333** [jaelpark/chamferwm#8]
Switching back and forth between chamfer and my current wm (which I need to do to properly configure it from a familiar environment) seems to crash chamfer. 

To reproduce:

1. Start chamfer in tty2
2. `chvt 1` 
3. `chvt 2`, then chamfer crashes with:
```
focus a000e AIGLX: Suspending AIGLX clients for VT switch 
[chamfer]: Error: failed to acquire a swap chain image
```

**Comment by jaelpark** [comment]
I couldn't get chamfer crash during my initial testing. Even before, I don't recall having any problems regarding this. Tried also with some animated windows open. Anyway, according to your log the crash happens when `vkAcquireNextImageKHR` fails, which in turn makes the compositor throw an exception and abort the execution. Do you have "Exit" written in your log after the error message? I could maybe improve the code to handle these error situations more gracefully, that might help.
